name: Release Docker Images
on:
  push:
#    branches:
#      - metric
#    paths:
#      - "python/sglang/version.py"
    tags:
      - "v*.*.*-metric"
      - "v*.*.*.*-metric"
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'kiritoxkiriko/sglang'
    runs-on: ubuntu-latest
    environment: 'prod'
    strategy:
      matrix:
        cuda_version: ['12.1.1']
        build_type: ['all']
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        run: |
          version=$(cat python/sglang/version.py | cut -d'"' -f2)

          #if [ "${{ matrix.cuda_version }}" = "11.8.0" ]; then
          #  cuda_tag="cu118"
          #elif [ "${{ matrix.cuda_version }}" = "12.1.1" ]; then
          #  cuda_tag="cu121"
          #elif [ "${{ matrix.cuda_version }}" = "12.4.1" ]; then
          #  cuda_tag="cu124"
          #else
          #  echo "Unsupported CUDA version"
          #  exit 1
          #fi
          # fix cuda version
          cuda_tag="cu121"

          #tag=v${version}-${cuda_tag}
          tag=v${version}

          #if [ "${{ matrix.build_type }}" = "all" ]; then
          #  tag_suffix=""
          #elif [ "${{ matrix.build_type }}" = "srt" ]; then
          #  tag_suffix="-srt"
          #else
          #  echo "Unsupported build type"
          #  exit 1
          #fi
          tag_suffix="-metric"

          docker build . -f docker/Dockerfile.metric --build-arg CUDA_VERSION=$cuda_tag --build-arg BUILD_TYPE=all -t ghcr.io/kiritoxkiriko/sglang:${tag}${tag_suffix} --no-cache
          docker push ghcr.io/kiritoxkiriko/sglang:${tag}${tag_suffix}

          if [ "$cuda_tag" = "cu121" ]; then
            docker tag ghcr.io/kiritoxkiriko/sglang:${tag}${tag_suffix} ghcr.io/kiritoxkiriko/sglang:latest${tag_suffix}
            docker push ghcr.io/kiritoxkiriko/sglang:latest${tag_suffix}
          fi
